name: Python CI for Attendance

on:
  workflow_call: {}  # Allows this workflow to be triggered by another workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./OT-Microservices/attendance

    # Step 4: Run tests with pytest
    - name: Run tests with pytest
      run: |
        pytest
      working-directory: ./OT-Microservices/attendance
