name: Python CI for Attendance

on:
  workflow_call: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: OT-Microservices/attendance

    - name: Run tests with pytest
      run: |
        pytest
      working-directory: OT-Microservices/attendance
