name: Attendance Folder CI

on:
  push:
    branches:
      - master
    paths:
      - 'attendance/**'  # Trigger only when files in the attendance folder change

jobs:
  trigger-attendance-workflow:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Call Attendance Workflow
      - name: Run Attendance Workflow
        run: |
          cd attendance
          if [ -f .github/workflows/python-ci.yml ]; then
            echo "Workflow exists in attendance folder. Proceeding..."
            exit 0
          else
            echo "Error: Workflow file not found in attendance/.github/workflows/"
            exit 1
          fi
