name: Trigger Attendance CI Workflow

on:
  push:
    branches:
      - master  # Trigger only on the master branch
    paths:
      - 'attendance/**'  # Trigger only when files in the attendance folder change

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Trigger the attendance build workflow
      - name: Trigger Attendance Build Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: ${{ github.repository }}  # Current repository
          workflow: '.github/workflows/python-ci.yml'  # Path to the second workflow
          ref: master  # Trigger on the master branch
