name: Attendance Folder CI

on:
  push:
    branches:
      - master
    paths:
      - 'attendance/**'  # Trigger only when files in the attendance folder change

jobs:
  trigger-attendance-workflow:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Dispatch Attendance Workflow
      - name: Dispatch Nested Attendance Workflow
        uses: peter-evans/workflow-dispatch@v2
        with:
          workflow: Python CI for Attendance
          ref: master
