name: Trigger Attendance CI Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'attendance/**'  # Trigger only when files in the attendance folder change

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up a GitHub API to trigger another workflow using `workflow_run`
      - name: Trigger Attendance Build Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const token = process.env.GITHUB_TOKEN;
            const repo = '${{ github.repository }}';
            const owner = '${{ github.repository_owner }}';
            const workflow_id = 'python-ci.yml';  # The name of the second workflow file

            // Call the workflow_dispatch event to trigger the second workflow
            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id,
              ref: 'refs/heads/master'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
