name: Trigger Attendance CI Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'attendance/**'  # Trigger only when files in the attendance folder change

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Trigger the second workflow directly via workflow_run event
      - name: Trigger Attendance Build Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: "python-ci.yml"    # The workflow file to trigger in the attendance folder
          ref: "refs/heads/master"     # Branch to trigger the workflow for
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
