name: Attendance Folder CI

on:
  push:
    branches:
      - master
    paths:
      - 'attendance/**'  # Trigger only when files in the attendance folder change

jobs:
  trigger-attendance-workflow:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Trigger the nested workflow via API
      - name: Dispatch Nested Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WORKFLOW_FILE="Python CI for Attendance.yml"
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)

          # Trigger the workflow_dispatch event
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/"$WORKFLOW_FILE"/dispatches \
            -d '{"ref":"master"}'
