name: Python CI for Attendance

on:
  workflow_dispatch:  # Triggered manually or by another workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install --no-cache-dir -r requirements.txt  # Install dependencies

      # Step 4: Verify the config.yaml file exists and is in the correct location
      - name: Check for config.yaml
        run: |
          if [ ! -f "attendance/config.yaml" ]; then
            echo "Error: config.yaml not found in attendance/"
            exit 1
          else
            echo "config.yaml found in attendance/"
          fi

      # Step 5: Set the correct environment variable for the config file
      - name: Set CONFIG_FILE environment variable
        run: echo "CONFIG_FILE=attendance/config.yaml" >> $GITHUB_ENV

      # Step 6: Run tests
      - name: Run Tests
        run: |
          pytest attendance/test_attendance_api.py --junitxml=test-results.xml  # Run tests

      # Step 7: Archive test results
      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml
