name: Python CI for Attendance

on:
  workflow_dispatch:  # Triggered manually or by another workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install --no-cache-dir -r requirements.txt  # Install dependencies

      # Step 4: Verify the config.yaml file exists and is in the correct location
      - name: Check for config.yaml
        run: |
          if [ ! -f "attendance/config/config.yaml" ]; then
            echo "Error: config.yaml not found in attendance/config/"
            exit 1
          else
            echo "config.yaml found in attendance/config/"
          fi

      # Step 5: Run tests
      - name: Run Tests
        run: |
          pytest attendance/test_attendance_api.py --junitxml=test-results.xml  # Run tests

      # Step 6: Archive test results
      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml

      # Step 7: Lint the codebase
      - name: Lint Code
        run: |
          pip install flake8
          flake8 . --max-line-length=88
